---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Сайт должен быть доступен на различных устройствах
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - Пользователь должен иметь возможность регистрации на сайте, что бы оставить данные для обратной связи
  - Пользователь должен иметь возможность просматривать историю заказов в лк
  - Пользователь должен иметь возможность сбросить фильтрацию
  - Пользователь должен видеть весь ассортимент, даже тот которого нет в наличие (возможно добавить ближайшую дату поставки)
  - Фильтр "по бренду" должен сортироваться только для определенной категории
  - Язык сайта должен определяться по пакетам клиента
  - Помимо кнопок для прелистывания "предыдущая\следующая", нужно добавить возможность выбрать номер страницы
  - Пользователь должне иметь возможность выбора валюты
